package com.example.marketing.ui.color

import androidx.compose.ui.graphics.Color

val CottonCandy = Color(0xFFFFB3BA)
val PeachFuzz = Color(0xFFFFDFBA)
val LemonChiffon = Color(0xFFFFFFBA)
val MintGreen = Color(0xFFBAFFC9)
val BabyBlue = Color(0xFFBAE1FF)
val PastelAqua = Color(0xFFD5F6FB)
val PastelSnow = Color(0xFFE5ECF8)
val PastelBlueGreen = Color(0xFFA5E3E0)
val PastelGreen = Color(0xFF77DD77)
val PastelBrown = Color(0xFF836953)
val PowderBlue = Color(0xFFB0E0E6)
val PastelTurquoise = Color(0xFF99C5C4)
val BlueGreenPastel = Color(0xFF9ADEDB)
val PersianPastel = Color(0xFFAA9499)
val MagicMint = Color(0xFFAAF0D1)
val LightGreen = Color(0xFFB2FBA5)
val PastelPurple = Color(0xFFB39EB5)
val PastelLilac = Color(0xFFBDB0D0)
val PastelPea = Color(0xFFBEE7A5)
val LightLime = Color(0xFFBEFD73)
val LightPeriwinkle = Color(0xFFC1C6FC)
val PaleMauve = Color(0xFFC6A4A4)
val PastelViolet = Color(0xFFCB99C9)
val BlushPink = Color(0xFFFEC8D8)
val LavenderPurple = Color(0xFF957DAD)
val PastelRose = Color(0xFFD291BC)
val Lumber = Color(0xFFFFDFD3)
val Thistle = Color(0xFFE0BBE4)
val PastelPink = Color(0xFFF5D1C3)
val Salmon = Color(0xFFFFB6A3)
val PastelTeal = Color(0xFFC4D7D1)
val SeaGreen = Color(0xFF5F9595)
val SunOrange = Color(0xFFF0BC68)
val LightBlue = Color(0xFFB2CEFE)
val PastelYellow = Color(0xFFFAF884)
val PastelMagenta = Color(0xFFF2A2E8)
val PastelRed = Color(0xFFFEA3AA)
val PastelOrange = Color(0xFFF8B88B)
val PastelPeach = Color(0xFFFFDAB9)
val PastelTan = Color(0xFFE9C9AA)
val PastelBerry = Color(0xFFED8698)
val PastelOchre = Color(0xFFD69759)
val PastelSkyBlue = Color(0xFFB4D9EF)
val PastelAquamarine = Color(0xFFB0E9D5)
val PastelBlue = Color(0xFFAEC6CF)
val PastelYellow2 = Color(0xFFFDFD96)
val PastelGreen2 = Color(0xFFBDFCC9)
val PastelPurple2 = Color(0xFFD8B2D1)
val PastelPink2 = Color(0xFFFFD1DC)
val PastelPeach2 = Color(0xFFFFE5B4)

